spring:
  application:
    name: @name@
    description: @description@
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
server:
  port: @server.port@
  rest:
    port: @server.rest.port@
    endpoint: mocketbank
---
adapter-mock-mpi:
  url: http://127.0.0.1:8018
---
mpi20:
  threeDsServerUrl: http://127.0.0.1:8018
  callbackUrl: http://127.0.0.1:8019
  threeDsMethodNotificationPath: /${server.rest.endpoint}/mpi20/three_ds_method_notification
  acsNotificationPath: /${server.rest.endpoint}/mpi20/acs_notification
  returnUrl: https://checkout.rbk.money/v1/finish-interaction.html
---
adapter-mock-bank:
  callbackUrl: http://127.0.0.1:8019
  pathCallbackUrl: /${server.rest.endpoint}/term_url{?termination_uri}
  pathRecurrentCallbackUrl: /${server.rest.endpoint}/rec_term_url{?termination_uri}
  pathP2pCallbackUrl: /${server.rest.endpoint}/p2p{?termination_uri}
  pathQpsCallbackUrl: /${server.rest.endpoint}/qps
  pathDigitalWalletCallbackUrl: /${server.rest.endpoint}/dw
  finishInteraction: https://checkout.rbk.money/v1/finish-interaction.html
---
cds:
  client:
    identity-document-storage:
      url: http://127.0.0.1:8021/v1/identity_document_storage
      networkTimeout: 5000
    storage:
      url: http://127.0.0.1:8021/v1/storage
      networkTimeout: 5000
---
hellgate:
  client:
    adapter:
      url: http://127.0.0.1:8023/v1/proxyhost/provider
      networkTimeout: 30000
---
fistful:
  client:
    adapter:
      url: http://127.0.0.1:8025/v1/ff_p2p_adapter_host
      networkTimeout: 30000
---
timer:
  redirectTimeout: 600
  qpsTimeout: 600
---
fixture:
  cards: classpath:fixture/cards.csv
  mobilephone: classpath:fixture/mobilephone.csv
  payout: classpath:fixture/payout.csv
---
rest-template:
  requestTimeout: 60000
  poolTimeout: 10000
  connectionTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200
---
error-mapping:
  file: classpath:fixture/errors.json
  patternReason: "'%s' - '%s'" # 'code' - 'description'
