spring:
  application:
    name: @name@
    description: @description@
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
server:
  port: @service.port@
  secondary:
    ports: @service.secondary.ports@
---
proxy-mocketbank-mpi:
  url: http://127.0.0.1:8018
---
proxy-mocketbank:
  callbackUrl: http://127.0.0.1:8019
---
cds:
  timeout: 5000
  url:
    keyring: http://127.0.0.1:8021/v1/keyring
    storage: http://127.0.0.1:8021/v1/storage
    idStorage: http://127.0.0.1:8021/v1/identity_document_storage
---
hellgate:
  client:
    adapter:
      url: http://127.0.0.1:8023/v1/proxyhost/provider
      networkTimeout: 30000
---
timer:
  timeout: 600
---
fixture:
  cards: classpath:fixture/cards.csv
---
restTemplate:
  networkTimeout: 5000
---
error-mapping:
  file: classpath:fixture/errors.json
  patternReason: "'%s' - '%s'" # 'code' - 'description'
