spring:
  application:
    name: @name@
    description: @description@
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
server:
  port: @server.port@
  rest:
    port: @server.rest.port@
    endpoint: mocketbank
---
adapter-mock-mpi:
  url: http://127.0.0.1:8018
---
adapter-mock-bank:
  callbackUrl: http://127.0.0.1:8019
  pathCallbackUrl: /${server.rest.endpoint}/term_url{?termination_uri}
  pathRecurrentCallbackUrl: /${server.rest.endpoint}/term_rec_url{?termination_uri}
---
cds:
  client:
    identity-document-storage:
      url: http://127.0.0.1:8021/v1/identity_document_storage
      networkTimeout: 5000
    storage:
      url: http://127.0.0.1:8021/v1/storage
      networkTimeout: 5000
---
hellgate:
  client:
    adapter:
      url: http://127.0.0.1:8023/v1/proxyhost/provider
      networkTimeout: 30000
---
timer:
  redirectTimeout: 600
---
fixture:
  cards: classpath:fixture/cards.csv
  mobilephone: classpath:fixture/mobilephone.csv
---
rest-template:
  requestTimeout: 60000
  poolTimeout: 10000
  connectionTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200
---
error-mapping:
  file: classpath:fixture/errors.json
  patternReason: "'%s' - '%s'" # 'code' - 'description'
